### ISSUE TITLE
Licence/acknowledgements

### ISSUE THREAD

**Issue by weka511** [reyman/netlogo-highlight#2]
Monsieur Reyman, thank you for making this script available. May I suggest that you add a licence, to clarify the use that others may make of your excellent code? I am about to start a project using NetLogo, and I also like to be able to acknowledge and tools that I use.

**Comment by reyman** [comment]
Hi,
Licence pushed on this work :)

**Comment by weka511** [comment]
Thanks, Monsieur Reyman.
